### ISSUE TITLE
Monolingual download not working 

### ISSUE THREAD

**Issue by lukasweymann** [hplt-project/OpusCleaner#139] opened 2023-12-15 15:05 UTC
Hi there, 

I have been testing the monolingual download and unfortunately it has always failed, for different languages and datasets. Is this still in development? 

Thanks

**Comment by XapaJIaMnu** [comment] 2023-12-15 15:26
Hmmm, it's intended to work. What error are you getting?

**Comment by lukasweymann** [comment] 2023-12-15 16:38
``` 
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/opuscleaner/download.py", line 74, in get_dataset
    with TemporaryDirectory(dir=path) as temp_extracted:
  File "/usr/lib/python3.10/tempfile.py", line 958, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
  File "/usr/lib/python3.10/tempfile.py", line 507, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: 'data/train-parts/tmpoizb57ga'
```

This is the log in the console from my last try. Sometimes I have seen as well another error saying "BadZipFile" or something alike

**Comment by jelmervdl** [comment] 2023-12-15 16:56
Could you check whether the data/train-parts folder exists? If not, does creating it fix it?

**Comment by jelmervdl** [comment] 2024-01-07 23:01
I think the problem is that monolingual download is just not properly supported yet. The download code expects a zip file when downloading, and the monolingual data just comes as a gzipped file. Which is okay! But just not supported.

Note that monolingual data is also not supported by the interface or the data discovery code yet.

I'll close this, and create a new issue discussing finishing support for monolingual data.

**Closed by jelmervdl** 2024-01-07 23:01 UTC
