### ISSUE TITLE
Setting languages for individual rules is redundant

### ISSUE THREAD

**Issue by eu9ene** [hplt-project/OpusCleaner#102] opened 2023-08-08 23:26 UTC
Currently, the UI asks me to specify the language pair again and again for different filtering rules. This is redundant because the language pair is already associated with the dataset. 

<img width="316" alt="Screenshot 2023-08-08 at 4 16 56 PM" src="https://github.com/hplt-project/OpusCleaner/assets/2486505/ec1619fa-b68c-41f4-b970-c33a072994eb">

Ideally, all the filtering rules should be universal except the language-specific ones like `segment_japanese` and languages codes shouldn't be present in the rule JSON to make them easily reusable. If the rule requires the language codes to look up something (for example `alpha_ratio`), they can be passed in runtime.

**Comment by kpu** [comment] 2023-08-09 19:26
Agreed; to do this we need a modicum of language code matching to deal with differences between data set label and langid labels like https://github.com/thammegowda/mtdata/tree/master/mtdata/iso

**Comment by kpu** [comment] 2023-08-09 20:13
Dupe of #45

**Closed by kpu** 2023-08-09 20:13 UTC
